//
//This class simulates enumeration for access levels
//
//Author: CERVELLO INC - Anil Tumati / Gennadiy Pervukhin (19-08-2013)
public class H_C_AccessLevel
{
	//
	//Constants
	//
	public static final String EDIT = 'Edit';
	public static final String READ = 'Read';
	public static final String NONE = 'None';
	
	/*public static final Map<String, Integer> MAP_OF_INTEGER_VALUES = new Map<String, Integer>();
	static
	{
		MAP_OF_INTEGER_VALUES.put(EDIT, 2);
		MAP_OF_INTEGER_VALUES.put(READ, 1);
		MAP_OF_INTEGER_VALUES.put(NONE, 0);
	}*/
	//
}