//
//This class provides constants for names of URL parameters
//
//Author: CERVELLO INC - Anil Tumati / Gennadiy Pervukhin (6-08-2013)
public class H_C_RequestParameters
{
	//
	//Constants
	//
	public static final String RETURN_URL = 'retURL';
	public static final String IS_PAGE_INLINE = 'inline';
	public static final String Id = 'id';
	public static final String CLOSE_TASK = 'close';
	public static final String SORTING_COLUMN = 'sortingColumn';
	public static final String PAGE_NUMBER = 'pageNumber';
	//
}