@isTest
private class MEP_ChatterDAOTests {
/*
	static void Aoutorize()
	{
			MEP_SiteLoginController controller = new MEP_SiteLoginController();
	    	controller.username='pete@40demo.com';
	    	controller.password ='123QWEasd';
	    	controller.login();
	    	System.assert(MEP_MepUserDAO.getCurrentMepUserId()!=null);
	}
    static testMethod void test_getChatterUser()
    {
    	Aoutorize();
		
    	System.assert(MEP_ChatterDAO.getAllChatterUsers().size()>0);
	 	System.assert(MEP_ChatterDAO.getAllPrivateMessages()!=null);
	 	System.assert(MEP_ChatterDAO.getUnreadConversationsCount()==0);
 	 	System.assert(MEP_ChatterDAO.getCurrentUserChatterGroups().size()==0);
    }
    
    static testMethod void test_getAllChatterUsers() {
    	Aoutorize();
        System.assert(MEP_ChatterDAO.getAllChatterUsers().size()>0);
    }*/
}